export type CatalogItem = { slug: string; title: string; group: "role" | "skill" | "practice"; isNew?: boolean };

const roleNames = ["Frontend", "Backend", "Full Stack", "Android", "DevOps", "DevSecOps", "Data Analyst", "SEO", "Inference Engineering", "AI Engineer", "AI and Data Scientist", "Data Engineer", "Machine Learning", "Product Design", "PostgreSQL", "iOS", "Blockchain", "QA", "Software Architect", "Cyber Security", "UX Design", "Technical Writer", "Game Developer", "Server Side Game Developer", "MLOps", "Product Manager", "Engineering Manager", "Developer Relations", "BI Analyst", "Network Engineer", "Forward Deployed Engineer"];
const skillNames = ["Claude Code", "Vibe Coding", "Python", "Python for Data Analysis", "R Programming", "Computer Science", "SQL", "OpenClaw", "React", "Vue", "Angular", "JavaScript", "TypeScript", "Node.js", "System Design", "LeetCode", "Java", "ASP.NET Core", "API Design", "Power BI", "Spring Boot", "Flutter", "C Programming", "C++", "Rust", "Go", "AI Product Builders", "Design and Architecture", "GraphQL", "React Native", "Design System", "Prompt Engineering", "MongoDB", "Linux", "Kubernetes", "Docker", "AWS", "Terraform", "Data Structures & Algorithms", "Redis", "Git and GitHub", "PHP", "Cloudflare", "AI Red Teaming", "AI Agents", "Next.js", "Code Review", "Kotlin", "HTML", "CSS", "Swift & Swift UI", "Shell / Bash", "Laravel", "Elasticsearch", "WordPress", "Django", "Ruby", "Ruby on Rails", "Scala"];
export function slugify(value: string) { return value.toLowerCase().replace(/\+/g, "plus").replace(/\./g, "").replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
export const catalog: CatalogItem[] = [
  ...roleNames.map(title => ({slug: slugify(title), title, group: "role" as const, isNew: ["SEO", "Inference Engineering"].includes(title)})),
  ...skillNames.map(title => ({slug: slugify(title), title, group: "skill" as const})),
  ...["AWS", "API Security", "Backend Performance", "Frontend Performance", "Code Review"].map(title => ({slug: slugify(title) + "-best-practices", title, group: "practice" as const})),
];
export type Topic = { id: string; title: string; summary: string; steps: string[]; exercise: string; resources: {title: string; url: string}[] };
export type LearningStage = { title: string; topics: string[] };
const mdn = {title: "MDN learning guides", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development"};
const gh = {title: "GitHub documentation", url: "https://docs.github.com/en/get-started"};
const topics: Record<string, Omit<Topic, "id">> = {
  internet: {title: "Internet", summary: "Understand the journey from a browser request to a server response. This makes errors, deployment, and performance easier to reason about.", steps: ["Explain what an IP address, domain, and DNS record do.", "Inspect an HTTP request and response in browser developer tools.", "Follow a request through a browser, network, web server, and database."], exercise: "Draw the request flow for opening a website and annotate each network step.", resources: [mdn]},
  http: {title: "HTTP & DNS", summary: "Learn the protocols that connect a client to a service: name resolution, methods, headers, status codes, and encrypted connections.", steps: ["Compare GET, POST, PUT, PATCH, and DELETE.", "Inspect headers and cookies for a request.", "Explain the difference between a 400, 401, 403, 404, and 500 response."], exercise: "Use curl or an API client to send three requests and explain their responses.", resources: [{title: "HTTP guide", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP"}]},
  browser: {title: "Browsers & hosting", summary: "Connect your local code to how a browser renders it and how a hosting platform serves it.", steps: ["Explain the DOM, CSSOM, and rendering pipeline.", "Use the network and performance panels.", "Publish a simple page and inspect its HTTPS connection."], exercise: "Deploy a static page and document the URL, DNS, and response headers.", resources: [mdn]},
  html: {title: "HTML", summary: "Create a meaningful document structure with semantic elements, links, images, tables, and accessible forms.", steps: ["Use headings and semantic landmarks in a sensible order.", "Give every form control an accessible label.", "Check keyboard navigation and image alternatives."], exercise: "Build an accessible personal profile with a contact form and project list.", resources: [{title: "Learn HTML", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content"}]},
  css: {title: "CSS", summary: "Style responsive layouts with the box model, cascade, Flexbox, Grid, and sensible typography.", steps: ["Explain specificity, inheritance, and the box model.", "Build a responsive layout with Flexbox and Grid.", "Test at narrow widths and with a larger text size."], exercise: "Recreate a responsive three-column card grid that becomes one column on a phone.", resources: [{title: "Learn CSS", url: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics"}]},
  javascript: {title: "JavaScript", summary: "Use the language of the web to transform data, handle events, and build interactive interfaces.", steps: ["Practise variables, functions, arrays, objects, and modules.", "Handle user input and update the DOM.", "Fetch data with async/await and explicit loading and error states."], exercise: "Build a searchable list backed by an API and handle an empty result and a failed request.", resources: [{title: "JavaScript guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide"}]},
  git: {title: "Git & GitHub", summary: "Track changes, work on branches, and collaborate through focused pull requests.", steps: ["Create commits that each describe one change.", "Create a branch, merge it, and resolve a simple conflict.", "Open a pull request with setup and verification instructions."], exercise: "Put a project on GitHub and submit a small improvement through a branch.", resources: [gh, {title: "Git book", url: "https://git-scm.com/book/en/v2"}]},
  packages: {title: "Package managers", summary: "Understand dependency manifests, lockfiles, scripts, version ranges, and repeatable installation.", steps: ["Install and remove a dependency with npm or pnpm.", "Explain why a lockfile belongs in a repository.", "Use scripts for development, testing, and production builds."], exercise: "Add a dependency, inspect the manifest and lockfile changes, and reproduce the install.", resources: [{title: "npm documentation", url: "https://docs.npmjs.com/"}]},
  react: {title: "React", summary: "Build interfaces from components and keep their data flow understandable with props, state, and effects.", steps: ["Extract a reusable component with clear props.", "Lift shared state to the closest common parent.", "Use effects for external synchronization and clean them up."], exercise: "Build a small task board with a filter, editable tasks, and saved state.", resources: [{title: "Learn React", url: "https://react.dev/learn"}]},
  typescript: {title: "TypeScript", summary: "Describe the shapes of your data and catch incorrect assumptions before your application runs.", steps: ["Type function parameters, return values, and component props.", "Use unions and narrowing to handle different states.", "Validate external data at runtime as well as typing it."], exercise: "Convert an API-driven JavaScript page to TypeScript without using any.", resources: [{title: "TypeScript handbook", url: "https://www.typescriptlang.org/docs/handbook/intro.html"}]},
  accessibility: {title: "Accessibility", summary: "Make your interface usable with a keyboard, assistive technology, and different viewing conditions.", steps: ["Use native controls and meaningful labels.", "Check focus order, focus visibility, and color contrast.", "Test empty, loading, validation, and success messages."], exercise: "Audit your form without a mouse and fix every unreachable control.", resources: [{title: "W3C accessibility tutorials", url: "https://www.w3.org/WAI/tutorials/"}]},
  node: {title: "Node.js", summary: "Run JavaScript on the server and build reliable services with asynchronous I/O and clear error handling.", steps: ["Understand the event loop and asynchronous operations.", "Create routes and validate request bodies.", "Handle errors and keep secrets in server configuration."], exercise: "Build a small JSON API with CRUD operations and consistent error responses.", resources: [{title: "Learn Node.js", url: "https://nodejs.org/en/learn"}]},
  sql: {title: "SQL & PostgreSQL", summary: "Model relational data and retrieve it safely with SQL queries, constraints, joins, and transactions.", steps: ["Create tables with primary keys, foreign keys, and useful constraints.", "Write SELECT queries with filters, joins, and aggregation.", "Use parameterized queries and database migrations."], exercise: "Design a task database and query tasks by owner, status, and due date.", resources: [{title: "PostgreSQL tutorial", url: "https://www.postgresql.org/docs/current/tutorial.html"}]},
  api: {title: "REST APIs", summary: "Design a predictable API with clear resources, HTTP semantics, validation, pagination, and documentation.", steps: ["Define resources and consistent route names.", "Choose appropriate status codes and error shapes.", "Add pagination, validation, and an API contract."], exercise: "Document and implement a paginated task endpoint with validation.", resources: [{title: "HTTP reference", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP"}, {title: "OpenAPI specification", url: "https://spec.openapis.org/oas/latest.html"}]},
  auth: {title: "Authentication", summary: "Distinguish who a user is from what they may do, and protect both browser and server boundaries.", steps: ["Compare sessions and tokens and their tradeoffs.", "Validate ownership on every protected server action.", "Learn secure cookie settings, password hashing, and CSRF protection."], exercise: "Protect an endpoint so a signed-in user can only access their own records.", resources: [{title: "OWASP cheat sheets", url: "https://cheatsheetseries.owasp.org/"}]},
  testing: {title: "Testing", summary: "Verify the behaviors that matter with focused unit, integration, and end-to-end checks.", steps: ["Test pure logic with representative inputs and edge cases.", "Test API success and failure behavior.", "Check one complete user journey including persistence."], exercise: "Test a form submission, validation failure, and a reload that preserves data.", resources: [{title: "Playwright documentation", url: "https://playwright.dev/docs/intro"}]},
  docker: {title: "Docker", summary: "Package an application and its environment so development and deployment use consistent dependencies.", steps: ["Write a small Dockerfile with an appropriate base image.", "Understand ports, volumes, environment variables, and networks.", "Run an application and database with Compose."], exercise: "Containerize your API and database and document how to start both.", resources: [{title: "Docker getting started", url: "https://docs.docker.com/get-started/"}]},
  cicd: {title: "CI / CD", summary: "Make builds and checks repeatable and connect a reviewed change to a reliable deployment.", steps: ["Run type checks and meaningful tests for each change.", "Build a reproducible production artifact.", "Keep deployment credentials in a secret store and plan rollback."], exercise: "Add a CI workflow that checks and builds your application.", resources: [{title: "GitHub Actions documentation", url: "https://docs.github.com/en/actions"}]},
  deployment: {title: "Deployment", summary: "Take a project from a local machine to a dependable public service with configuration, monitoring, and recovery.", steps: ["Separate local and production configuration.", "Deploy with HTTPS and server-side secrets.", "Inspect logs and practise reverting a broken change."], exercise: "Publish your app and write a setup guide another developer can follow.", resources: [{title: "Cloudflare developer documentation", url: "https://developers.cloudflare.com/"}]},
  project: {title: "Build a complete project", summary: "Connect your new skills in an application with a clear purpose and a complete, tested user journey.", steps: ["Choose a small problem and define the core user flow.", "Build the interface, API, and persistent data model.", "Test, deploy, and document your decisions and limitations."], exercise: "Ship a task manager, habit tracker, or learning dashboard with a working backend.", resources: [gh]},
  portfolio: {title: "Portfolio & interviews", summary: "Show what you built and explain why it works. A concise project story is more useful than a list of tools.", steps: ["Write a case study with a problem, architecture, and demo.", "Explain a difficult bug and the evidence used to resolve it.", "Practise coding, API design, and project walkthroughs."], exercise: "Record a three-minute demonstration and write one focused project case study.", resources: [gh]},
  python: {title: "Python", summary: "Write readable scripts and applications with Python's core types, control flow, functions, and modules.", steps: ["Practise lists, dictionaries, iteration, and comprehensions.", "Use virtual environments and package dependencies.", "Handle files, exceptions, and type hints."], exercise: "Write a command-line script that cleans a CSV file and produces a summary.", resources: [{title: "Python tutorial", url: "https://docs.python.org/3/tutorial/"}]},
  data: {title: "Data analysis", summary: "Turn raw records into useful answers while checking assumptions, missing values, and uncertainty.", steps: ["Inspect types, missing records, and unusual values.", "Group, filter, join, and summarize data.", "Choose a chart that answers a specific question."], exercise: "Analyze a public dataset and present three findings with their limitations.", resources: [{title: "pandas getting started", url: "https://pandas.pydata.org/docs/getting_started/index.html"}]},
  statistics: {title: "Statistics", summary: "Use distributions, variation, probability, and careful evaluation to distinguish evidence from noise.", steps: ["Compare mean, median, spread, and outliers.", "Explain sampling and the difference between correlation and causation.", "Use confidence intervals and holdout data appropriately."], exercise: "Compare two groups in a dataset and explain what you can and cannot conclude.", resources: [{title: "NIST statistics handbook", url: "https://www.itl.nist.gov/div898/handbook/"}]},
  ml: {title: "Machine learning", summary: "Train a simple baseline, measure its performance, and understand the data and errors before adding complexity.", steps: ["Split training, validation, and test data without leakage.", "Choose metrics suited to the problem.", "Compare a baseline model and inspect its mistakes."], exercise: "Train a classifier and document its evaluation and failure cases.", resources: [{title: "scikit-learn getting started", url: "https://scikit-learn.org/stable/getting_started.html"}]},
  ai: {title: "AI applications", summary: "Build useful model-powered features with explicit contracts, evaluation, and clear failure handling.", steps: ["Define the input and output your application needs.", "Validate structured output and handle missing or malformed responses.", "Evaluate examples and account for cost, latency, and uncertainty."], exercise: "Build a document assistant that cites its sources and handles missing information.", resources: [{title: "Gemini API documentation", url: "https://ai.google.dev/gemini-api/docs"}]},
  linux: {title: "Linux & shell", summary: "Work confidently with files, processes, permissions, services, and remote machines.", steps: ["Navigate, search, pipe, and redirect output.", "Inspect processes, permissions, and network connections.", "Use SSH and write a small repeatable shell script."], exercise: "Write a script that backs up a folder and checks whether a service is running.", resources: [{title: "GNU Bash manual", url: "https://www.gnu.org/software/bash/manual/"}]},
  cloud: {title: "Cloud infrastructure", summary: "Understand compute, storage, networking, access control, and observability before scaling a service.", steps: ["Compare virtual machines, containers, and serverless functions.", "Apply least privilege and protect secrets.", "Set up logs, health checks, and a simple cost budget."], exercise: "Deploy a small service and document its architecture and estimated cost.", resources: [{title: "AWS documentation", url: "https://docs.aws.amazon.com/"}]},
  security: {title: "Security fundamentals", summary: "Protect the data and trust boundaries in your application with a practical threat model and secure defaults.", steps: ["Identify inputs, assets, and trust boundaries.", "Prevent injection, broken access control, and exposed secrets.", "Keep dependencies current and record security assumptions."], exercise: "Threat-model your app and verify access checks for another user's data.", resources: [{title: "OWASP developer guide", url: "https://owasp.org/www-project-developer-guide/"}]},
  design: {title: "Product & UX design", summary: "Start with a user problem and turn it into an understandable flow, prototype, and tested interface.", steps: ["Identify the user's task, context, and pain points.", "Sketch a flow and a low-fidelity prototype.", "Observe a usability test and revise the design."], exercise: "Prototype a learning planner and test its main flow with three people.", resources: [{title: "Material Design foundations", url: "https://m3.material.io/foundations"}]},
  architecture: {title: "System architecture", summary: "Design a system around its requirements and explain the tradeoffs in data, communication, reliability, and scale.", steps: ["Define functional requirements and realistic limits.", "Draw service boundaries and data flows.", "Compare caching, queues, replication, and failure handling."], exercise: "Design a URL shortener and explain how it behaves when a component fails.", resources: [{title: "Azure architecture center", url: "https://learn.microsoft.com/en-us/azure/architecture/"}]},
  algorithms: {title: "Data structures & algorithms", summary: "Choose appropriate structures and reason about the time and space required by your solution.", steps: ["Practise arrays, hash maps, stacks, queues, and trees.", "Explain Big O and tradeoffs between solutions.", "Solve problems with two pointers, binary search, and graph traversal."], exercise: "Solve one problem two ways and compare complexity and edge cases.", resources: [{title: "OpenDSA learning materials", url: "https://opendsa-server.cs.vt.edu/"}]},
};

const specificSequences: Record<string, string[][]> = {
  "full-stack": [["internet", "http", "browser"], ["html", "css", "javascript"], ["git", "packages", "typescript"], ["react", "accessibility", "testing"], ["node", "api", "auth"], ["sql", "security", "architecture"], ["docker", "cicd", "deployment"], ["project", "portfolio"]],
  frontend: [["internet", "http", "browser"], ["html", "css", "accessibility"], ["javascript", "git", "packages"], ["react", "typescript", "api"], ["testing", "security", "deployment"], ["project", "portfolio"]],
  backend: [["internet", "http", "linux"], ["node", "python", "git"], ["sql", "api", "auth"], ["architecture", "security", "testing"], ["docker", "cicd", "deployment"], ["project", "portfolio"]],
};
const officialLinks: Record<string, string> = {react:"https://react.dev/learn",vue:"https://vuejs.org/guide/introduction.html",angular:"https://angular.dev/tutorials",python:"https://docs.python.org/3/tutorial/",java:"https://dev.java/learn/",rust:"https://doc.rust-lang.org/book/",go:"https://go.dev/learn/",kotlin:"https://kotlinlang.org/docs/home.html",flutter:"https://docs.flutter.dev/",django:"https://docs.djangoproject.com/",ruby:"https://www.ruby-lang.org/en/documentation/",scala:"https://docs.scala-lang.org/",php:"https://www.php.net/manual/en/",laravel:"https://laravel.com/docs",nextjs:"https://nextjs.org/docs",mongodb:"https://www.mongodb.com/docs/",kubernetes:"https://kubernetes.io/docs/home/",terraform:"https://developer.hashicorp.com/terraform/docs",redis:"https://redis.io/docs/latest/",graphql:"https://graphql.org/learn/",elasticsearch:"https://www.elastic.co/docs",wordpress:"https://developer.wordpress.org/",cloudflare:"https://developers.cloudflare.com/","c-programming":"https://en.cppreference.com/w/c.html","c-plusplus":"https://en.cppreference.com/w/","nodejs":"https://nodejs.org/en/learn","react-native":"https://reactnative.dev/docs/getting-started","ruby-on-rails":"https://guides.rubyonrails.org/","spring-boot":"https://docs.spring.io/spring-boot/","aspnet-core":"https://learn.microsoft.com/en-us/aspnet/core/","power-bi":"https://learn.microsoft.com/en-us/power-bi/","r-programming":"https://cran.r-project.org/manuals.html",android:"https://developer.android.com/courses",ios:"https://developer.apple.com/tutorials/", "swift-and-swift-ui":"https://developer.apple.com/tutorials/swiftui", "claude-code":"https://code.claude.com/docs/en/overview"};

export function getTopic(id: string): Topic {
  if (topics[id]) return {id, ...topics[id]};
  const item = catalog.find(c => c.slug === id);
  const title = item?.title ?? id.replace(/-/g, " ");
  const domain = /ai|inference|prompt|claude|openclaw|vibe/.test(id) ? "AI workflows" : /design|product|ux/.test(id) ? "product development" : /engineer|network|cloud|aws|kubernetes|terraform/.test(id) ? "systems and operations" : "software development";
  const officialUrl = officialLinks[id === "cplusplus" ? "c-plusplus" : id];
  return {id, title, summary: `Explore ${title} through its core concepts, a small practical implementation, and careful validation. Connect what you learn to ${domain} rather than memorizing terminology.`, steps: [`Read an introduction to ${title} and explain its main purpose.`, "Set up a small example and change one behavior at a time.", "Document your decisions, test edge cases, and build a project that demonstrates the skill."], exercise: `Build a small ${title} project, include setup instructions, and explain one important tradeoff.`, resources: officialUrl ? [{title: `${title} official documentation`, url: officialUrl}] : /ai|inference|prompt|claude|openclaw|vibe/.test(id) ? topics.ai.resources : /design|product|ux/.test(id) ? topics.design.resources : /engineer|cloud|network|aws/.test(id) ? topics.cloud.resources : [gh]};
}

export function getStages(item: CatalogItem): LearningStage[] {
  let sequence = specificSequences[item.slug];
  if (!sequence) {
    const s = item.slug;
    if (/data|machine|mlops|bi-analyst|power-bi|statistics/.test(s)) sequence = [["python", "sql", "git"], ["data", "statistics", "algorithms"], [s, "ml", "ai"], ["api", "cloud", "testing"], ["project", "portfolio"]];
    else if (/devops|linux|docker|kubernetes|aws|terraform|cloudflare|shell|network/.test(s)) sequence = [["linux", "http", "git"], [s, "docker", "cloud"], ["cicd", "security", "architecture"], ["deployment", "testing"], ["project", "portfolio"]];
    else if (/security|secops|red-teaming/.test(s)) sequence = [["internet", "linux", "http"], ["security", s, "auth"], ["api", "cloud", "testing"], ["project", "portfolio"]];
    else if (/design|ux|product|writer|relations|manager/.test(s)) sequence = [["design", s], ["accessibility", "architecture"], ["project", "testing"], ["portfolio"]];
    else if (/ai|inference|prompt|claude|openclaw|vibe/.test(s)) sequence = [["python", "git", "api"], ["ai", s, "data"], ["security", "testing", "deployment"], ["project", "portfolio"]];
    else if (/android|ios|flutter|react-native|kotlin|swift/.test(s)) sequence = [[s, "git", "algorithms"], ["design", "accessibility"], ["api", "sql", "auth"], ["testing", "deployment"], ["project", "portfolio"]];
    else if (/architect|system-design|computer-science|leetcode|structures|game|blockchain/.test(s)) sequence = [["algorithms", s, "git"], ["architecture", "sql", "api"], ["security", "cloud", "testing"], ["project", "portfolio"]];
    else if (/frontend|react|vue|angular|html|css|javascript|typescript|design-system/.test(s)) sequence = [["internet", "html", "css"], [s, "javascript", "typescript"], ["react", "api", "accessibility"], ["testing", "deployment"], ["project", "portfolio"]];
    else sequence = [[s, "git", "packages"], ["api", "sql", "auth"], ["testing", "security", "architecture"], ["deployment", "project", "portfolio"]];
  }
  const used = new Set<string>();
  return sequence.map((ids, i) => ({title: ["Start with the foundations", "Build your core skills", "Connect the pieces", "Make it reliable", "Practise and ship", "Go deeper", "Ship with confidence", "Show your work"][i] ?? "Keep learning", topics: ids.filter(id => {if (used.has(id)) return false; used.add(id); return true;})})).filter(s => s.topics.length);
}

export type LessonPack = {id: string; title: string; subtitle: string; lessons: string[]; color: string; topic: string};
export const packs: LessonPack[] = [
  {id:"git-fundamentals",title:"Git Fundamentals",subtitle:"From your first commit to collaborating with a team.",lessons:["Repositories & commits", "Inspecting changes", "Branching", "Merging", "Resolving conflicts", "Remote repositories", "Pull requests", "A team workflow"],color:"#ef5a3c",topic:"git"},
  {id:"internet-fundamentals",title:"Internet Fundamentals",subtitle:"Follow a request through DNS, HTTP, servers, and browsers.",lessons:["How the web connects", "IP addresses & DNS", "HTTP requests", "Status codes & headers", "HTTPS", "Browsers & hosting"],color:"#a78bfa",topic:"internet"},
  {id:"html-fundamentals",title:"HTML Fundamentals",subtitle:"Structure real pages with clear, accessible markup.",lessons:["Document structure", "Text & headings", "Links & images", "Semantic elements", "Lists & tables", "Forms & labels", "Accessibility", "Build a profile page"],color:"#fb923c",topic:"html"},
  {id:"css-fundamentals",title:"CSS Fundamentals",subtitle:"Style responsive pages and understand why your layout works.",lessons:["Selectors & the cascade", "The box model", "Typography", "Colors & contrast", "Flexbox", "CSS Grid", "Responsive layouts", "Build a card grid", "Positioning", "Transitions"],color:"#60a5fa",topic:"css"},
  {id:"javascript-foundations",title:"JavaScript Foundations",subtitle:"Learn the language by making things that respond.",lessons:["Values & variables", "Functions", "Arrays & objects", "Control flow", "DOM & events", "Modules", "Promises", "Fetching data", "Error handling", "Build a task list"],color:"#facc15",topic:"javascript"},
  {id:"node-cli",title:"Build CLI Apps with Node.js",subtitle:"Turn small scripts into useful command-line tools.",lessons:["The Node.js runtime", "Arguments & input", "Files & paths", "Dependencies", "Errors & exit codes", "Build a CLI tool"],color:"#4ade80",topic:"node"},
];
export type ProjectIdea = {id: string; title: string; category: string; difficulty: string; description: string; tasks: string[]; skills: string[]};
export const projects: ProjectIdea[] = [
  {id:"portfolio",title:"Personal Portfolio",category:"Frontend",difficulty:"Beginner",description:"Introduce yourself, showcase three projects, and make it easy to get in touch.",tasks:["Create semantic pages for your profile and projects.", "Build a responsive layout with accessible navigation.", "Add clear project descriptions and links.", "Deploy and check the site at phone and desktop widths."],skills:["HTML", "CSS", "Accessibility"]},
  {id:"task-tracker",title:"Task Tracker",category:"Frontend",difficulty:"Beginner",description:"Create, edit, complete, and filter tasks with progress that survives a reload.",tasks:["Add a form with input validation.", "Support editing, completing, and removing tasks.", "Add status filters and an empty state.", "Save tasks and verify a reload restores them."],skills:["JavaScript", "Local storage", "Forms"]},
  {id:"weather-app",title:"Weather Dashboard",category:"Frontend",difficulty:"Intermediate",description:"Search a city and present a useful weather summary with clear loading and error states.",tasks:["Choose a documented weather API and read its usage limits.", "Search locations and request forecasts.", "Display units, times, and source information.", "Handle invalid locations and network errors."],skills:["React", "APIs", "TypeScript"]},
  {id:"expense-api",title:"Expense Tracker API",category:"Backend",difficulty:"Intermediate",description:"Build an API for recording expenses and understanding spending by month and category.",tasks:["Design a relational schema for users, categories, and expenses.", "Implement CRUD routes with validation.", "Protect access to each user's records.", "Test aggregation queries and document the API."],skills:["Node.js", "SQL", "Authentication"]},
  {id:"url-shortener",title:"URL Shortener",category:"Backend",difficulty:"Intermediate",description:"Turn a long URL into a short link and measure redirects without exposing private data.",tasks:["Validate target URLs and generate unique IDs.", "Store links and implement the redirect endpoint.", "Add rate limits and expiration behavior.", "Test collisions, missing links, and invalid inputs."],skills:["REST", "Databases", "Testing"]},
  {id:"learning-platform",title:"Learning Platform",category:"Full Stack",difficulty:"Advanced",description:"Combine a course catalog, lessons, and saved learner progress in one complete app.",tasks:["Model courses, lessons, enrollment, and progress.", "Build a searchable course catalog and lesson viewer.", "Implement authenticated progress updates.", "Test a complete learning journey and deploy."],skills:["React", "Node.js", "PostgreSQL"]},
  {id:"data-explorer",title:"Public Data Explorer",category:"Data",difficulty:"Intermediate",description:"Clean a public dataset and give readers a clear way to explore its patterns and limits.",tasks:["Choose a dataset with a documented source and license.", "Clean missing values and explain transformations.", "Build filters and two informative charts.", "Write findings with limitations and reproducible steps."],skills:["Python", "pandas", "Visualization"]},
  {id:"ai-assistant",title:"Document Assistant",category:"AI",difficulty:"Advanced",description:"Answer questions from a set of documents with citations and a clear response when evidence is missing.",tasks:["Define which documents the assistant may use.", "Retrieve relevant passages for a question.", "Generate answers with source references.", "Evaluate unsupported questions, malformed responses, and latency."],skills:["Python", "AI APIs", "Evaluation"]},
  {id:"deploy-pipeline",title:"Deployment Pipeline",category:"DevOps",difficulty:"Intermediate",description:"Make a small application reproducible from source checkout through production deployment.",tasks:["Containerize an application and its dependencies.", "Add CI checks and a production build.", "Configure secrets and deployment steps.", "Add a health check and demonstrate a rollback."],skills:["Docker", "CI / CD", "Cloud"]},
];
export type Guide = {id: string; title: string; category: string; intro: string; sections: {title: string; body: string}[]};
export const guides: Guide[] = [
  {id:"start-full-stack",title:"Your first path into full-stack development",category:"Getting started",intro:"A useful learning plan connects each new concept to something you can build. Start small and keep a working application at every stage.",sections:[{title:"Learn the web before the framework",body:"Build a page with semantic HTML and responsive CSS. Add JavaScript to handle a form or load data. Inspect a browser request so you understand where the information comes from."},{title:"Add one layer at a time",body:"Use React when you need reusable interactive components. Build a small server API next, then persist records in a database. Connect the interface to the API before adding more features."},{title:"Show a complete journey",body:"Choose one feature that works from input to saved data. Validate the input, explain errors, test the flow, and deploy it. Write down what you would improve next."}]},
  {id:"git-workflow",title:"A Git workflow for your first team project",category:"Guide",intro:"Small commits and clear pull requests make it easier for teammates to understand and review your work.",sections:[{title:"Keep changes focused",body:"Start a branch for one feature or fix. Inspect your diff before committing and describe the behavior that changed. Keep unrelated formatting out of the same commit."},{title:"Review together",body:"Open a pull request with the problem, your solution, and how to verify it. Ask another teammate to try the core flow. Resolve feedback before merging."},{title:"Handle conflicts carefully",body:"Read both versions, agree on the desired behavior, and test the combined result. A conflict is a disagreement in text; resolving it still requires checking the application."}]},
  {id:"api-design",title:"Design APIs that are easy to use",category:"Backend",intro:"A clear API sets expectations about inputs, outputs, errors, and ownership before clients depend on it.",sections:[{title:"Model resources",body:"Choose stable resource names and use HTTP methods consistently. Validate incoming data and return appropriate status codes with a predictable error shape."},{title:"Protect records",body:"Authentication identifies the user. Authorization decides whether that user can access a particular record. Check ownership on the server for every protected operation."},{title:"Document the edges",body:"Explain pagination, sorting, time formats, and limits. Include example requests and responses for both success and failure. Test those examples against your implementation."}]},
  {id:"react-state",title:"Where should React state live?",category:"Frontend",intro:"State belongs close to the code that owns it. Move it upward only when multiple components need to coordinate.",sections:[{title:"Keep local decisions local",body:"A dropdown's open state can stay in the dropdown. Form values can live in the form until another part of the page needs them. Avoid a global store for every interaction."},{title:"Lift shared state",body:"If a filter and a list use the same selection, store it in their nearest shared parent and pass values and callbacks through props."},{title:"Avoid duplicated values",body:"Derive filtered results and totals from the underlying records. Storing both the input and its calculated result creates two places that can disagree."}]},
  {id:"project-readme",title:"Write a README someone can actually follow",category:"Career",intro:"Good documentation helps a reviewer run your project and understand the decisions behind it.",sections:[{title:"Explain the purpose",body:"Start with the problem, who the application serves, and the main flow. Include a screenshot or short demo with a link to the live application."},{title:"Make setup repeatable",body:"List prerequisites, exact installation commands, required configuration names, and how to start the project. Provide an example environment file without real credentials."},{title:"Be concrete about evidence",body:"Describe what you tested and the limitations you know about. Show an architectural decision with its tradeoff rather than a long list of technologies."}]},
  {id:"learning-pace",title:"Build a learning plan you can sustain",category:"Getting started",intro:"A roadmap is a guide to useful next steps. Progress comes from understanding and practice, not checking every box as quickly as possible.",sections:[{title:"Set a realistic budget",body:"Choose the hours you can spend in an ordinary week. Reserve time for debugging and revisiting material. Break a larger project into milestones you can finish in that budget."},{title:"Use proof of understanding",body:"For each topic, write a short explanation and complete one practical exercise. If you already know a skill, demonstrate it and move to the next useful step."},{title:"Adjust the plan",body:"Review your progress weekly. Reduce scope when a task is larger than expected and update your priorities when your target role changes."}]},
  {id:"testing-first-project",title:"What to test in your first full-stack project",category:"Guide",intro:"Start with the behavior that would matter most if it broke: saving data, protecting access, and explaining failures.",sections:[{title:"Test the core flow",body:"Submit valid input, verify the saved record, and reload. Check that the right user can retrieve it and another user cannot."},{title:"Check failure states",body:"Try invalid input, a missing record, and a failed service request. The application should explain the problem and preserve work the user can recover."},{title:"Make checks repeatable",body:"Automate the checks that protect important logic. Keep a short manual checklist for keyboard navigation and responsive layouts."}]},
  {id:"ai-apps",title:"Build an AI feature with clear failure handling",category:"AI",intro:"Model output needs the same care as any external service: validation, evaluation, and an honest response when a request cannot be completed.",sections:[{title:"Define a contract",body:"Describe the exact data the interface needs. Request structured output where supported and validate every field before using it."},{title:"Handle service failures",body:"Expect quota limits, invalid credentials, timeouts, and incomplete output. Return actionable messages and avoid replacing an error with invented content."},{title:"Evaluate the useful behavior",body:"Collect realistic examples including missing evidence and ambiguous input. Measure whether the output fulfills the task and records its uncertainty."}]},
];
